name: Cron Job for Backup and Automation

on:
  schedule:
    # Runs the workflow every day at 2:00 AM UTC
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-api-requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Send POST Request to /backup-db/
      env:
        API_URL: ${{ secrets.API_URL }}
      run: |
        curl -X POST "$API_URL/backup-db/" 

    - name: Send POST Request to /automate-all/
      env:
        API_URL: ${{ secrets.API_URL }}
      run: |
        curl -X POST "$API_URL/automate-all/"